# Generated by Django 4.2.5 on 2023-09-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='название')),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='описание')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='', verbose_name='изображение')),
                ('link', models.CharField(blank=True, max_length=150, null=True, verbose_name='ссылка')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='изображение'),
        ),
    ]
