# Generated by Django 4.2.5 on 2023-09-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_lesson_course_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lessons',
            field=models.ManyToManyField(to='course.lesson'),
        ),
    ]
