# Generated by Django 4.2.5 on 2023-09-26 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_remove_course_title_course_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0002_alter_payment_options_remove_payment_paid_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='course_paid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='date_of_payment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='lesson_paid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(default=1, verbose_name='amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='course_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='course.course', verbose_name='course payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='datetime'),
        ),
        migrations.AddField(
            model_name='payment',
            name='lesson_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='course.lesson', verbose_name='lesson payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('loading', 'loading'), ('cancel', 'cancel'), ('success', 'success')], default='loading'),
        ),
        migrations.AddField(
            model_name='payment',
            name='verify_payment_number',
            field=models.PositiveIntegerField(default=1, verbose_name='verify payment number'),
            preserve_default=False,
        ),
    ]
