# Generated by Django 4.2.5 on 2023-09-26 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import datetime



class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0008_remove_course_title_course_name'),
        ('payment', '0003_alter_payment_options_remove_payment_course_paid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'payment', 'verbose_name_plural': 'payments'},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='course_payment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='lesson_payment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='verify_payment_number',
        ),
        migrations.AddField(
            model_name='payment',
            name='course_paid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='course_paid'),
        ),
        migrations.AddField(
            model_name='payment',
            name='date_of_payment',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 9, 26, 8, 21, 34, 711905, tzinfo=datetime.timezone.utc), verbose_name='date_of_payment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='lesson_paid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.lesson', verbose_name='lesson_paid'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_amount',
            field=models.IntegerField(default=1, verbose_name='payment_amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cach', 'Cach'), ('transfer', 'Transfer')], default=1, max_length=150, verbose_name='payment_method'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_id',
            field=models.CharField(default=1, max_length=300, verbose_name='stripe_id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='user'),
            preserve_default=False,
        ),
    ]
